export default {
  answer: {
    REQUEST: 'ANSWER_QUESTION_REQUEST',
    SUCCESS: 'ANSWER_QUESTION_SUCCESS',
    FAILURE: 'ANSWER_QUESTION_FAILURE',
  },
  get: {
    REQUEST: 'GET_QUESTION_REQUEST',
    SUCCESS: 'GET_QUESTION_SUCCESS',
    FAILURE: 'GET_QUESTION_FAILURE',
  }
};
